- hosts: nodes

  tasks:
    - debug: msg="preparing mounts..."
    - name: Install exfat-fuse
      apt: pkg=exfat-fuse state=present

    - mount: 
       name: "/media/seqdata"
       src: "LABEL=SEQDATA"
       fstype: "exfat"
       state: "present"
       passno: '0'
       dump: '0'
       opts: "nofail,auto,noatime,rw,user"
